# Generated by Django 4.1.7 on 2024-07-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ans',
        ),
    ]
