# Generated by Django 4.1.7 on 2024-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_response_quiz_active_textanswer_response_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
